### ISSUE TITLE
when i compile mxnet on the ubuntu15.10,i got this compile error.

### ISSUE THREAD

**Issue by tanger830** [dmlc/mxnet#1135]
ndarray.cc:(.text+0x848)：对‘void mxnet::ndarray::EvalClip<mshadow::gpu>(mshadow::TBlob const&, float const&, float const&, mshadow::TBlob*, mxnet::RunContext)’未定义的引用
...
：对‘mxnet::opt::call_sgd_update_gpu(mxnet::RunContext, mshadow::TBlob, mshadow::TBlob, float, mxnet::opt::SGDParam const&)’未定义的引用
...
collect2: error: ld returned 1 exit status
Makefile:167: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

i have no idea to overcome this, any suggestion is appreciated.

**Comment by piiswrong** [comment]
try make clean_all

**Comment by tanger830** [comment]
thanks for your suggestion, but make clean_all does not solve the problem, the same compile errors prompt again.

**Comment by piiswrong** [comment]
Try make a fresh clone of the newest code and compile again.

**Comment by tanger830** [comment]
yes， my code is out of date. thanks, but i get another error:
'''
/usr/bin/ld: skipping incompatible /usr/local/cuda-7.5/lib64/libcuda.so when searching for -lcuda
/usr/bin/ld: cannot find -lcuda
'''
does mxnet not support cuda-7.5?

**Comment by qiaohaijun** [comment]
I am using cuda 7.5, mxnet work well

**Comment by tanger830** [comment]
so, any suggestion?

**Comment by mli** [comment]
have you installed the nvidia driver? libcuda.so is often located at

/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib64/libcuda.so

**Comment by qiaohaijun** [comment]
when you run the 'locate' cmd in your bash, can you find the path of libcuda.so?

``` bash
$ locate libcuda.so
```

**Comment by tanger830** [comment]
Thanks All!
i can locate the libcuda.so which link to libcuda.so.352.63
but the ld said it's incompatible
here is the details of run locate
```
 ~/lib/mxnet$ locate libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.352.63
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.352.63
/usr/local/cuda-7.5/doc/man/man7/libcuda.so.7
/usr/local/cuda-7.5/targets/x86_64-linux/lib/libcuda.so
/usr/local/cuda-7.5/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/share/man/man7/libcuda.so.7.gz
```
and the output of ld:
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
Makefile:153: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
```

**Comment by piiswrong** [comment]
Can you compile other program that use cuda? This looks like either your cuda is not correctly installed or your compiler tool chain is broken.

**Comment by tanger830** [comment]
i have successfully compiled Caffe and Torch with support of cuda.

**Comment by winstywang** [comment]
What is the version of GCC?

**Comment by tanger830** [comment]
gcc version is 4.9.3

**Comment by winstywang** [comment]
@tanger830 Try degrade to gcc 4.8.4 I met similar problems using higher version of gcc/g++

**Comment by tanger830** [comment]
i have replace gcc and g++ with gcc-4.8 and g++-4.8 in config.mk which version is 4.8.5, but the same ld error appears again :(

**Comment by winstywang** [comment]
Do you have several CUDA installed on your machine?

**Comment by jianminsun** [comment]
I had a similar problem. I fixed it by following two steps: 
make clean_all
source ~/.bashrc

**Comment by kleinash** [comment]
Hi. I am getting the same error as right at the start: 
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

Ubuntu 14.04 

I checkout, rebuilt as suggested, but this hasnt solved the issue.

**Comment by taozhijiang** [comment]
try to modify the Makefile, -lcuda -> -lcudart

**Comment by yesoun** [comment]
Hi All,
I am trying to run this program, http://www.ieap.uni-kiel.de/et/people/kruse/tutorials/cuda/tutorial01o/web01o/tutorial01o.pdf


I am having this output in terminal when I try make:
g++ main.o cuda_wrapper.o -o main -L/usr/local/cuda-5.5/lib64 -lcuda -lcudart `OcelotConfig -l`
/usr/bin/ld: cannot find -lcuda
/usr/bin/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
make: *** [main] Error 1

this is the make file that they have used:
CC=g++
LINKER_DIRS=-L/usr/local/cuda-5.5/lib64
LINKER_FLAGS=-lcuda -lcudart
NVCC=nvcc
CUDA_ARCHITECTURE=20
OCELOT=`OcelotConfig -l`

all: main

main: main.o cuda_wrapper.o
	$(CC) main.o cuda_wrapper.o -o main $(LINKER_DIRS) $(LINKER_FLAGS) $(OCELOT)

main.o: main.cpp
	$(CC) main.cpp -c -I .

cuda_wrapper.o: cuda_wrapper.cu
	$(NVCC) -c cuda_wrapper.cu -arch=sm_$(CUDA_ARCHITECTURE)

clean:
	rm -f main.o cuda_wrapper.o main

**Comment by kleinash** [comment]
Sorry to necro this post. But I am struggling with this same issue. I was using mxnet just fine a few months ago, now some updates later. Changing the Makefile from -lcuda to -lcudart has not worked and I am getting this error: 

collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

when trying to compile mxnet from scratch with CUDA enabled.

**Comment by anttttti** [comment]
same error here, -lcudart doesn't fix. Ubuntu 16.04, CUDA V8.0.26

**Comment by mli** [comment]
try to remove this line https://github.com/dmlc/mxnet/blob/master/Makefile#L52 ?

bin/im2rec is not necessary anymore. there is a python version.

**Comment by anttttti** [comment]
compiles without the "BIN += bin/im2rec" line

**Comment by kkgadiraju** [comment]
@meanmee  I was able to build the code using @anttttti's suggestion to remove the line "BIN+=bin/im2rec"

**Comment by meanmee** [comment]
@kkgadiraju that's awesome, it works!
