### ISSUE TITLE
how does mxnet search work?

### ISSUE THREAD

**Issue by George19890617** [dmlc/mxnet#2253]
I try to search key word, but it seems doesn't work? For example I enter Forward in the blank, I just get, 

> Search
From here you can search these documents. Enter your search words into the box below and click "search". Note that the search function will automatically search for all of the words. Pages containing fewer words won't appear in the result list.

 is that a bit inconvenient to readers?

**Comment by tornadomeet** [comment]
yes, the [doc website](http://mxnet.readthedocs.io/en/latest/) do not support search yet. maybe we should add it for readers @tqchen @mli

**Comment by mli** [comment]
it works if build locally, but breaks at readthedocs. it probably due to
wrong jquery.js files.

**Comment by tqchen** [comment]
should be fixed by https://github.com/dmlc/mxnet/pull/2265

**Comment by sxjscience** [comment]
I find that I still cannot search in http://mxnet.readthedocs.io/ .
