### ISSUE TITLE
[C++] the image classification C++ example might be broken

### ISSUE THREAD

**Issue by thirdwing** [dmlc/mxnet#2600]
I always got the same result as below.

```
Best Result: [ chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour] id = 490, accuracy = 1.00000000
```

**Comment by piiswrong** [comment]
what network are you using?

**Comment by antinucleon** [comment]
I tried python Inception/Inception-Full, similar observation. I am checking
too.

On Sat, Jul 2, 2016 at 9:34 PM Eric Junyuan Xie <notifications@github.com>
wrote:

> what network are you using?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2600#issuecomment-230134992>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13rtSudPT7jrFkt400kK571cyPfxoks5qRzvrgaJpZM4JDzHM>
> .
>
-- 
Sent from mobile phone

**Comment by thirdwing** [comment]
I am using the Inception-BN model https://github.com/dmlc/mxnet/blob/master/example/cpp/image-classification/image-classification-predict.cc#L168

**Comment by antinucleon** [comment]
Should be same problem to the pretrained model. I think there is something
wrong in master but not C++ example.

On Sat, Jul 2, 2016 at 10:36 PM Qiang Kou (KK) <notifications@github.com>
wrote:

> I am using the Inception-BN model
> https://github.com/dmlc/mxnet/blob/master/example/cpp/image-classification/image-classification-predict.cc#L168
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2600#issuecomment-230136680>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13oIPdBOa-9ce_O-uKqbXF_nCclCxks5qR0pEgaJpZM4JDzHM>
> .
>
-- 
Sent from mobile phone

**Comment by tornadomeet** [comment]
i met this too,but when use cudnn,it will be OK.(may be it due to the BN operator,not very sure.)

**Comment by thirdwing** [comment]
I think this is broken by this commit https://github.com/dmlc/mxnet/commit/6c27c3b7388f979b57c4cc2ccd895054ef0fd1c3

**Comment by piiswrong** [comment]
@thirdwing Could you verify if removing L92 fixes this? I'm not sure why. Alternatively try add fix_gamma=False to all your bn symbols in json

**Comment by piiswrong** [comment]
@thirdwing @tornadomeet should be fixed with https://github.com/dmlc/mxnet/pull/2606

**Comment by tornadomeet** [comment]
@piiswrong @thirdwing My problem is still exist, related #2617
